description: Loading search data to ElasticSearch
schedule_interval: 11 05 * * *
tags:
  - search
default_args:
  owner: airflow
  result_type: pickle
  retries: 1
  work_conn_id: s3work
  work_type: s3
factory: Python
